name: Run TinyCoder Help

on:
  issues:
    types:
      - labeled

jobs:
  run_tinycoder_help:
    # Only run if the label added is 'tinycoder'
    if: github.event.label.name == 'tinycoder'
    runs-on: ubuntu-latest
    permissions:
      issues: write # Needed to comment on the issue

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Install TinyCoder
      run: python3 -m pip install git+https://github.com/koenvaneijk/tinycoder.git

    - name: Run TinyCoder help
      run: tinycoder --help

    - name: Echo event context
      run: |
        echo "Issue Event Context:"
        cat $GITHUB_EVENT_PATH

    - name: Post comment to issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_REPO: ${{ github.repository }}
      run: gh issue comment $ISSUE_NUMBER --repo $GH_REPO --body "Hello world!"