name: Run TinyCoder Help

on:
  issues:
    types:
      - labeled

jobs:
  run_tinycoder_help:
    # Only run if the label added is 'tinycoder'
    if: github.event.label.name == 'tinycoder'
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Install TinyCoder
      run: python3 -m pip install git+https://github.com/koenvaneijk/tinycoder.git

    - name: Run TinyCoder help
      run: tinycoder --help