name: Run TinyCoder Help

on:
  issues:
    types:
      - labeled

jobs:
  run_tinycoder_help:
    # Only run if the label added is 'tinycoder'
    if: github.event.label.name == 'tinycoder'
    runs-on: ubuntu-latest
    permissions:
      issues: write       # Needed to comment on the issue
      contents: write     # Needed to push branches and create PRs
      pull-requests: write # Needed to create PRs

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch all history for all branches and tags
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Use a recent Python 3 version

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create and checkout branch
      id: create_branch
      run: |
        BRANCH_NAME="tinycoder-issue-${{ github.event.issue.number }}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
        git checkout -b $BRANCH_NAME

    - name: Install TinyCoder
      run: python3 -m pip install git+https://github.com/koenvaneijk/tinycoder.git

    - name: Run TinyCoder (assuming it commits changes)
      # Pass necessary info like issue body, number, etc. if needed
      # Example: tinycoder --issue-body "${{ github.event.issue.body }}"
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: tinycoder --code "${{ github.event.issue.body }}"

    - name: Push changes
      run: git push origin ${{ steps.create_branch.outputs.BRANCH_NAME }}

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        BRANCH_NAME: ${{ steps.create_branch.outputs.BRANCH_NAME }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        gh pr create \
          --repo $GH_REPO \
          --base main `# Or your default branch` \
          --head $BRANCH_NAME \
          --title "TinyCoder changes for Issue #${ISSUE_NUMBER}" \
          --body "Automated changes generated by TinyCoder to address issue #${ISSUE_NUMBER}."

    - name: Post comment to issue
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        GH_REPO: ${{ github.repository }}
        PR_URL: $(gh pr list --repo $GH_REPO --head ${{ steps.create_branch.outputs.BRANCH_NAME }} --json url -q '.[0].url') # Get PR URL
      run: |
        if [ -z "$PR_URL" ]; then
          echo "Could not find PR URL. Skipping comment."
        else
          gh issue comment $ISSUE_NUMBER --repo $GH_REPO --body "Created Pull Request for this issue: $PR_URL"
        fi